[request_definition]
r = sub, obj, act # 请求格式：主体（用户）、资源、操作

[policy_definition]
p = sub, obj, act # 策略格式：与请求格式对应，存储合法的（用户, 资源, 操作）组合

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act || r.sub=="19971030"